### ISSUE TITLE
Cities in Brazil

### ISSUE THREAD

**Issue by maelle** [openaq/openaq-fetch#128]
@dolugen noticed some "?".

I think the corresponding cities should be:
- Cap��o Redondo -> Capão Redondo
- Paul��nia -> Paulistânia or rather Paulínia?
- Paul��nia-Sul -> Paulistânia-Sul or maybe rather Paulínia-Sul? Paulínia is a location name already in the data apparently.
- S��o José do Rio Preto -> São José do Rio Preto
- Tatu�� -> Tatuí

**Comment by masalmon** [comment]
Then the same problematic names can be found again as location names. I could not see new wrong names when looking at location names.

**Comment by masalmon** [comment]
Before today I thought that only French words could include "â"!

**Comment by jflasher** [comment]
@masalmon where are you seeing this? Everything should be in UTF-8 and it looks good in the database and also when I view it in the browser or terminal. 

![](https://www.dropbox.com/s/kz0sl83soylt1rg/Screenshot%202016-03-23%2009.37.01.png?dl=1)

I think we do have some of these '?' floating around, specifically in EPA data since that's what comes out of their data files, but I don't see it happening for Brazil for me.

**Comment by masalmon** [comment]
in R and in @dolugen's browser, but it might be due to my locale settings then!

**Comment by jflasher** [comment]
Hmm, actually looked into this a bit more and there is an older measurement that is showing the '?' so it might be that messing things up, will investigate more!

**Comment by masalmon** [comment]
That's what happens to people breaking my unit tests. Good luck!

**Comment by jflasher** [comment]
Ok, I'm actually seeing this show up in https://api.openaq.org/v1/locations?country=BR. Looks like we have some instances where accents are properly handled and some where they're not, leading to measurements for 1 actual location to split across a couple different ones. Not sure if this is due to historical artifacts with the way we were ingesting data, or if this is due to random errors on the source page. Best way may be to change the data currently in the system and see if this happens again in the future.

**Comment by masalmon** [comment]
Well done! :sunny:

**Comment by masalmon** [comment]
In your link I see both
"location":"Campinas-V.Uniao"
and
"location":"Campinas-V.União"

**Comment by dolugen** [comment]
A quite late follow-up here.

Some names with replacement characters (the question marks in dark diamonds) are still there.

Also, as masalmon reported, the cities list contain unaccented versions. The latter weren't fixed in #97 where only properly accented names were handled.

**Comment by olafveerman** [comment]
## 1. replacement characters
As far as I can tell, there are 6 locations with a replacement character (�) that don't come through AirNow:

| location | measurements |
| --- | :---: |
| `S��o José do Rio Preto` | [1 result](https://api.openaq.org/v1/measurements?location=S%EF%BF%BD%EF%BF%BDo%20Jos%C3%A9%20do%20Rio%20Preto) |
| `Tatu��` | [1 result](https://api.openaq.org/v1/measurements?location=Tatu��) |
| `Cap��o Redondo` | [1 result](https://api.openaq.org/v1/measurements?location=Cap��o%20Redondo) |
| `Gobernaci��n` | [1 result](https://api.openaq.org/v1/measurements?location=Gobernaci��n) |
| `Paul��nia` | [1 result](https://api.openaq.org/v1/measurements?location=Paul��nia) |
| `Paul��nia-Sul` | [1 result](https://api.openaq.org/v1/measurements?location=Paul��nia-Sul) |

Each of them have only one result.
I think we can update those location names since there is no conflicting measurement.

## 2. different variations of same location
There are a lot of duplicate Brazilian locations. `Paulínia Sul` seems to have 4 variants for example:

[`Paulínia Sul`](https://api.openaq.org/v1/locations?location=Paul%C3%ADnia%20Sul)
[`Paulínia-Sul`](https://api.openaq.org/v1/locations?location=Paul%C3%ADnia-Sul)
[`Paulínia - Sul`](https://api.openaq.org/v1/locations?location=Paul%C3%ADnia%20-%20Sul)
[`Paulinia Sul`](https://api.openaq.org/v1/locations?location=Paulinia%20Sul)

The proper response seems to be to merge those, but that doesn't seem like an easy task. Especially since  this might result in duplicate measurements.

Thoughts @jflasher ?

**Comment by dolugen** [comment]
Related to openaq/openaq-api#301

**Comment by majesticio** [comment]
I queried the DB for the replacement characters and name variations and did not see any. Closing issue - but feel free to reopen with new information.
