### ISSUE TITLE
RK Puram (location in Delhi)

### ISSUE THREAD

**Issue by masalmon** [openaq/openaq-fetch#172]
Why does RK Puram have two names, first RK Puram and then R K Puram?

![rkpuram](https://cloud.githubusercontent.com/assets/8360597/15647570/a9a67180-2664-11e6-8c5b-bf36db881405.png)

**Comment by masalmon** [comment]
East Arjun Nagar also changes names over time, I had not noticed this before posting the screenshot.

**Comment by jflasher** [comment]
RK Puram changes most likely because we changed data source and they handled it different between sources. East Arjun Nagar is only coming from the one data source, so they must handle it different at times within their own system.

Things like this are what makes me just want to use coordinates for everything. :(
