### ISSUE TITLE
Wrong lastUpdated date

### ISSUE THREAD

**Issue by danielfdsilva** [openaq/openaq-fetch#186]
I've noticed that for some locations the last update date is one hour ahead. So far I've only seen this in Chile, but it may be happening elsewhere.
![selection_001](https://cloud.githubusercontent.com/assets/1090606/17587899/0d825e98-5fc3-11e6-950b-32b4aa55fa1e.png)

At the time of the screenshot the time was 11:30 UTC

**Comment by abarciauskas-bgse** [comment]
I noticed there is some descrepency in when some locations for Chile (CL) for this source (SINCA) have last updated as one hour difference - for example at this time some were last updated at 5pm on March 7, 2021 (assuming this is UTC) and some were last updated at 6pm the same day. However, since this parameter identifies the time where the most recent measurement was updated for the given location, it could be that some locations were updated "1 hour ago" and some locations were updated "2 hours ago"
