### ISSUE TITLE
Missing PM 2.5 sources in Delhi

### ISSUE THREAD

**Issue by aatishb** [openaq/openaq-fetch#237]
Hi. I ran into a few issues when pulling PM 2.5 data from Delhi. It seems the official data sources available for Delhi are:

1. DPCC: http://www.dpccairdata.com/dpccairdata/display/index.php
2. CPCB: http://www.cpcb.gov.in/CAAQM/mapPage/frmindiamap.aspx
3. US embassy: https://in.usembassy.gov/embassy-consulates/new-delhi/air-quality-data/

In almost all cases, the openAQ PM 2.5 data comes from the CPCB data (the only exception being the US embassy). However, I'm finding that the CPCB data is not very reliable, e.g. it's either [missing data](https://openaq.org/#/compare/R%20K%20Puram/Anand%20Vihar/Punjabi%20Bagh?parameter=pm25&_k=4ahf9p) for many days in the week, or in a [few cases](https://openaq.org/#/compare/Civil%20Lines/IGI%20Airport?parameter=pm25&_k=kbu4ft) hasn't been updated in the last 18 months. (The one exception seems to be the [Income Tax Office](https://openaq.org/#/compare/Income%20Tax%20Office/US%20Diplomatic%20Post%3A%20New%20Delhi?parameter=pm25&_k=4zzwu9) which is currently providing very regular data.) Meanwhile, the DPCC is providing regular data (every 15 minutes) for five of these locations, but openAQ doesn't pull this data as far as I can tell.

So my suggestions are to:
1. Incorporate DPCC data (if possible). This would help fill in the blanks for the CPCB data & also seems to be more regularly updated. (I'm not even sure if there are two different instruments.. it seems more liekly that CPCB is just infrequently pulling DPCC data for these 5 locations.)
2. Include missing CPCB data. There are a few CPCB sites reporting PM 2.5 that aren't listed in openAQ (Dilshad Garden, Shadipur, Dwarka). Would be great if these could be incorporated as well.

I've summarized the issues I encountered in this [spreadsheet](https://docs.google.com/spreadsheets/d/1XUhLl_rHkw6OdCvd1PQir3RjibCcoKhMx1jMqQqKL_4/edit?usp=sharing).

I'm new here, so apologies if I'm missing something obvious. Great work on openAQ, it's super helpful and valuable work!

**Comment by dolugen** [comment]
@aatishb Thank you for compiling the spreadsheet! It would be certainly helpful to update the Indian data sources. 

DPCC was used in the past, but was removed (couldn't recall the reasoning, because CPCB was introduced?). The sources were re-inserted and marked as inactive, and the adapter can be looked up in the repo history.

I'll review the spreadsheet along with the sources, but I like your suggestions, and think it's best to include the missing sources.

Here's a copy of @aatishb's spreadsheet in [Markdown format](https://guides.github.com/features/mastering-markdown/):

Location                       | openAQ source | CPCB              | DPCC    | Comments                                                                 | Last Reading
-------------------------------|---------------|-------------------|---------|--------------------------------------------------------------------------|-------------
Anand Vihar                    | CPCB          | Present           | **Present** | **DPCC data is missing from openAQ and seems more frequent that CPCB data**  | 30 hours    
Civil Lines                    | CPCB          | Present           | **Present** | **DPCC data is missing from openAQ and CPCB data is 18 months out of date.** | **18 months**   
Delhi Technological University | CPCB?         | Page not loading  | Absent  | Data is 1 month out of date. CPCB data not loading.                      | 29 days     
IGI Airport                    | CPCB          | Present           | Absent  | **CPCB data is 18 months out of date**                                       | **18 months**   
Income Tax Office              | CPCB          | Present           | Absent  | CPCB data is frequent & looks reliable                                   | 36 minutes  
Mandir Marg                    | CPCB          | Present           | **Present** | **DPCC data is missing from openAQ and seems more frequent that CPCB data**  | 27 hours    
Punjabi Bagh                   | CPCB          | Present           | **Present** | **DPCC data is missing from openAQ and seems more frequent that CPCB data**  | 27 hours    
R K Puram                      | CPCB?         | Not shown on page | **Present** | **DPCC data is missing from openAQ and CPCB data is not currently listed**   | 38 hours    
Siri Fort                      | CPCB?         | Present           | Absent  | CPCB sensor seems to be giving some faulty data (readings maxing out)    | 36 minutes  
US Diplomatic Post: New Delhi  | US            | Absent            | Absent  |                                                                          | 51 minutes  
Dilshad Garden                 | **Absent**        | Present           | Absent  | **openAQ doesn't list this, but data is available from CPCB**                |             
Shadipur                       | **Absent**        | Present           | Absent  | **openAQ doesn't list this, but data is available from CPCB**                |             
Dwarka                         | **Absent**        | Present           | Absent  | **openAQ doesn't list this, but data is available from CPCB**                |

**Comment by dolugen** [comment]
Yes, CPCB replaced DPCC in #52.

**Comment by jflasher** [comment]
Hey @aatishb, thanks for the info! In situations where there is a more top-level source for the data in a region, we prefer to go with that source. This is why we switched to CPCB from DPCC. Our preferred approach would be to let CPCB know and help them figure out how to better make all their data available, rather than just take it from DPCC.

I think I saw somewhere else that the issue with the missing locations is due to difference in naming of parameters (`pm2.5` vs `pm 2.5`) which is an issue that can be fixed in the adapter.

**Comment by nishadhka** [comment]
@jflasher thanks for clarification but, as of now CPCB is not sourcing the DPCC data, it could be loosing the data from DPCC

**Comment by dolugen** [comment]
> I think I saw somewhere else that the issue with the missing locations is due to difference in naming of parameters (`pm2.5` vs `pm 2.5`) which is an issue that can be fixed in the adapter.
This may be the case for me some the locations. I'm going to check if #238 fixes them.

**Comment by dolugen** [comment]
Location                                  | pm25 available after #238 | 
--------------------------------------|------------------------------------
IHBAS (Dilshad Garden)         |  yes
Shadipur                                 |  yes
NSIT Dwarka (Dwarka)           |  yes

Other updates for the spreadsheet:
* R K Puram's current data is available

#238 will be merged shortly, so pm25 from above locations will be available in the API then.

**Comment by dolugen** [comment]
In my feed, I see a comment from @nishadhka on this issue. But I don't see one here.

**Comment by nishadhka** [comment]
Sorry I deleted that comment, it was about missing DPCC data which are currently live. I read other issues related to this and so.

**Comment by dolugen** [comment]
Ah, okay. No worries.

**Comment by aatishb** [comment]
Hi all, thanks for your work on this!

@dolugen appreciate your looking into this and fixing the pm25 vs pm2.5 issue. 

@jflasher I understand your point of view re: top-level sources. I just wanted to stress that in practice the CPCB data is considerably harder to work with. They are fairly unreliable at polling DPCC (inconsistent time intervals & many windows with missing data), lower in time resolution (I think), and in some cases nearly 2 years out of date. In the interim while they improve their data pipeline, if openAQ had an option to directly access DPCC data, it would allow for a more regular & consistent dataset (particularly if the DPCC adapter has already been written). However I totally understand if it's not worth the trouble for a short-term solution.

**Comment by jflasher** [comment]
There is already a DPCC adapter that could be turned on. I think the bigger problem is how to avoid duplicates. There are no unique IDs for each station (even station names change within the same source sometimes 😭 ) so I'm not sure we have a foolproof way to avoid duplication. This is my main concern with using aggregators plus original source.
