### ISSUE TITLE
Handle preferredUnit outside of adapter modules

### ISSUE THREAD

**Issue by dolugen** [openaq/openaq-fetch#250]
I think it would be a time-saver if the `preferredUnit` field were handled outside of an adapter, somewhere like `fetch.js`.

The unit can be derived from the pollutant name. Where pm25 comes in, µg/m³ is set. It's already in the API, so I don't see why you need to set it again.

But as the name implies, I think there could be other units than the preferred ones? In those cases, the adapter could override the unit name.

**Comment by jflasher** [comment]
The tricky thing is that each source may have the measurements in different physical units. So it's not just making sure the names match up, but there is the potential to actually do real work to change values. 

https://github.com/openaq/openaq-fetch/blob/develop/lib/utils.js#L79 (which should get run at the end of an adapter) will handle changing between like units. But if something is in a volumetric concentration (ppm), we will not convert to a mass concentration (µg/m³). 

If I'm understanding your idea correctly, I don't think we can do it because not all pm25 measurements *are* in µg/m³ coming from the source and we need the adapter to say what units the measurement *is* in, so it can be properly converted by our system.

**Comment by dolugen** [comment]
Oh, I could've messed up the Queensland units, then. Fortunately, looking at their 2015 archives, they use our preferred units :sweat_smile:
