### ISSUE TITLE
No data from UK/DEFRA source

### ISSUE THREAD

**Issue by RocketD0g** [openaq/openaq-fetch#292]
Reported: OpenAQ hasn’t aggregated any data from the stations in the UK for the past 5 days:
https://openaq.org/#/countries/GB?_k=q9b5qb

"Based on https://status.openaq.org/, looks like we’re failing to load the DEFRA URL. "

The DEFRA url may have changed, and if that is the only change, this may be a simple fix.

**Comment by RocketD0g** [comment]
The url itself seems to be working to me: 
https://uk-air.defra.gov.uk/latest/currentlevels

**Comment by RocketD0g** [comment]
A colleague sent this info on potential methods for accessing the data.

> I think there are two possibilities [here](https://uk-air.defra.gov.uk/data/atom-dls/), one is an Atom service (see here) and the other is SOS (see [here](https://uk-air.defra.gov.uk/data/sos/about/)).

Items to check out: Is the data available in real-time? With coordinates? etc.

**Comment by jflasher** [comment]
Ok, DEFRA source (via scraping) should now be fixed. Did a quick look at the other two methods mentioned above as it'd be nice to use some other than scraping. A few quick observations.

## Atom Feed
- It looks like we'd have to follow a path like https://uk-air.defra.gov.uk/data/atom-dls/auto/2017/atom.en.xml -> https://uk-air.defra.gov.uk/data/atom-dls/auto/2017/GB_FixedObservations_2017_ABD.atom.en.xml -> https://uk-air.defra.gov.uk/data/atom-dls/observations/auto/GB_FixedObservations_2017_ABD.xml. 
- There are coordinates in here, which is good (well they're a bounding box, but we can make a center point from that)
- We'd have to do this for each of the ~160 locations, that seems way too heavy to do on each fetch
- Each of the final xmls provides all data since the beginning of the year, again way to heavy to do every 10 minutes.

Unless I'm missing something, doesn't look like this would be a good alternative.

## SOS API
This looks really promising, it should allows us to get the data via a RESTful API and consume JSON 💃 . The base url looks like `https://uk-air.defra.gov.uk/sos-ukair/api/v1/`. Did a quick check of stations and it reported back a whole bunch of things, which is great. There are coordinates. I'm unsure of how best to achieve our use case though. We don't want to have to query the system 500 times to get 3 pollutants from ~160 stations. Would be good to try and reach out to someone over there and see how to best handle that.
