### ISSUE TITLE
Investigate EEA's new direct download option

### ISSUE THREAD

**Issue by jflasher** [openaq/openaq-fetch#298]
EEA rolled out a new access option that may be more reliable, check it out. 

More info to come.

**Comment by lhufnagel** [comment]
Email from May 18th

Dear users of the EEA Up-to-date air quality download service
In the last two years we have seen a quickly growing interest in access to the up-to-date air quality download service. We are of cause very happy for the huge interest, but it has also pushed our services to the limit and even though we have been upgrading and improving the platform several times in the last year, we have not been able to keep up with the demand.

To provide a better service, we have therefore developed a simplistic direct download solution which we believe will cover the majority of downloads and hopefully also your need.

The direct download solution is now available on the UTD download page: 
http://discomap.eea.europa.eu/map/fme/AirQualityUTDExport.htm

Every 12 hours we extract the last 48 hours of data per country and the 8 major pollutants. Not all countries delivers all of these 8 pollutants so in total it is around 180 files. The files are only available in the CSV2-format which is known from the on-demand download service.
The file names are static, making it easy for your automated downloads to access the latest data. 
Sample url (Andorra, Ozone): http://discomap.eea.europa.eu/map/fme/latest/AD_O3.csv
Generic url: http://discomap.eea.europa.eu/map/fme/latest/<countrycode>_<pollutant>.csv
The data are provided in UTC+1 (the timezone is included in CSV2) and as with the on-deman service, only hourly data are provided.

We have decided only to offer the last 48 hours of data with this option. This is due to the fact, that we receive updates to already delivered data, and in order to keep the files in sync with our database we do not want to keep the old and possible out-of-sync files.

The old on-demand download service will continue to be supported, but we hope many of your will find the direct download useful and hereby removing the pressure on the on-demand download service.

Should you have any questions to the new option, please do not hesitate to contact me.

Kind regards
Peter Kjeld

**Comment by maxgrossman** [comment]
@jflasher @lhufnagel - beginning work on this [here](https://github.com/openaq/openaq-fetch/tree/adapter/direct-eea). 

I'll use links like the one above in each country's source. Coords will come from [this](http://discomap.eea.europa.eu/map/fme/metadata/PanEuropean_metadata.csv) metadata file that, among other information, has EPSG:4979 coordinates for stations. 

I'll do this first for countries in #309 and push often!

**Comment by jflasher** [comment]
@maxgrossman I'm wondering if it's better to actually start by bringing in data for all the already existing EEA sources rather than starting with the ones that aren't currently included? My thinking here is that those already added are generally the more important ones and look to currently be having issues being fetched via old mechanism. Also, they're the bigger ones like France and Germany so if there are any issues, it'll happen there and not on the smaller remaining ones.

**Comment by maxgrossman** [comment]
@jflasher per usual your suggestions make sense! I'll work on the existing countries.

**Comment by jflasher** [comment]
Don't worry, given enough time, I will start speaking gibberish!

**Comment by maxgrossman** [comment]
@jflasher @lhufnagel - just wanted to give a quick update. I'm one more push (to handle timezones) away from having an adapter in a PR we can test.

Anyhow, the direct download seems to work nicely w/around 1 min runtime for the countries I have tested (France, Germany, Belgium). 

One thing I'll have to make sure is that the same stations reported in direct downloads are the same as those being reported currently.

**Comment by lhufnagel** [comment]
Awesome! 👍

**Comment by jflasher** [comment]
@maxgrossman this is great! And glad to hear it's working nice and efficiently. I wouldn't worry too much about matching the stations. We'll just be going with whatever is coming out of their system, I don't think we should be doing a ton of work trying to match it up to what they reported previously.

**Comment by olafveerman** [comment]
For the review of the EEA adapter, I did some investigation into how they handle time:

1. In real life, Portugal is currently +1 UTC  
[Today's CSV with O3](http://discomap.eea.europa.eu/map/fme/latest/PT_O3.csv)
2. In real life, Poland is currently +2 UTC  
[Today's CSV with O3](http://discomap.eea.europa.eu/map/fme/latest/PL_O3.csv)
3. In real life, Latvia is currently +3 UTC  
[Today's CSV with O3](http://discomap.eea.europa.eu/map/fme/latest/LV_O3.csv)

All of them report timestamps in `+01:00`. This is in line with the email [quoted above](https://github.com/openaq/openaq-fetch/issues/298#issuecomment-303090375). It's easy to convert this to UTC.

Local time requires more wrangling, but each record in the CSV has a field `network_timezone` that contains an indication of the local timezone. This would allow us to calculate the local time:

```
http://dd.eionet.europa.eu/vocabulary/aq/timezone/UTC+02
```

I think we can assume that they handle DST properly, but we could check if a January extract for Latvia reports `network_timezone` to be `http://dd.eionet.europa.eu/vocabulary/aq/timezone/UTC+01`

cc @maxgrossman @jflasher @dolugen

**Comment by jflasher** [comment]
Thanks @olafveerman! I think we're using the network_timezone in the current adapter to get UTC/local https://github.com/openaq/openaq-fetch/blob/develop/adapters/eea.js#L116

For the adapter, I'd be in favor of gathering the data as they provide it and if they're not properly taking into account DST, updating them. Rather than trying to do all the work on our side to try and properly account for that (because that seems like a nightmare).

**Comment by maxgrossman** [comment]
@olafveerman @jflasher - some of our country csvs (Andora notably) have blank records in the `network name` field.

This makes the `city` property in the returned measurements also blank. To make dry runs pass, I have a string reading 'unused' as a place holder when there is not a network name record.

I'd imagine this isn't satisfactory - so wanted to know if you guys had ideas for alternatives. I could implement reverse geocoding perhaps for the no-name scenarios.

Regarding the timezone question, I've written the adapter to snaps off the UTC offset from the `network_timezone` field. Then I use that to map a time zone string valid for moment.tz

Anyhow, I just pushed the code that reflects all of this. Just wanted to keep the heads up regarding the nameless `network name` scenarios in this thread.

**Comment by jflasher** [comment]
the problem is even worse than @maxgrossman states, see #234. That network name is not necessarily the city, even though sometimes it is. Would be great to figure out a way to handle this. Reverse geocoding every 10 minutes on this scale scares me both in a time it takes to do it sense and a potential cost sense.

**Comment by maxgrossman** [comment]
@jflasher - I'll test out the reverse geocoding w/germany to see if the time change is signifcant and let you know. Hopefully I can quash your fears with some success!

**Comment by maxgrossman** [comment]
reverse geocoding works lovely (w/same runtime) in Andora since it has only a handful of stations. But, all others ramp up majorly in run time...

**Comment by jflasher** [comment]
Thanks for looking into this! I like the idea of doing it the first way. The data script would generate a static file that we store along with the adapter right? If we only set a city if one is present from reverse geocoding, then locations without a city will fail the insert and we'll see them show up in fetch status. That'd be an indication we'd need to run the data script again to get new location cities.

**Comment by maxgrossman** [comment]
Yes that's the idea. We could store the files as `eea-countryname-cities.json` somewhere, then just read it in on each fetch.

**Comment by jflasher** [comment]
Seems like it'd work to me. Anyone else have any thoughts?

cc/ @dolugen

**Comment by maxgrossman** [comment]
Quick update here @jflasher and @dolugen :

I just added the initial script for generating these locations. 

I'm reverse geocoding using [pelias](https://github.com/pelias/pelias). One thing to note here is that we can make 25,000 requests a month (so updates to the locations data need be only for new stations, not all stations most likely).

One big limitation with reverse geocoding some 14k stations is this rate limiting. Not only does this prevent us from doing the geocoding in parallel, it also requires us to throttle our requests. The result - this script is slow!

With rate limiting in mind, I'll make the script only reverse geocodes if it sees there are stations in EEA's metadata file that we don't have in our station location json.

Lastly - @kamicut and I chatted yesterday about how to update our records dynamically on each adapter run by: 
1. having an adapter, when it spatial selection fails, ping the the eea-location script to run to grab new stations
2. host these stations in a small db (or even s3 if a json files is ok)

This solution sound ok?

**Comment by jflasher** [comment]
Yeah, I think this sounds good, with one exception, I don't think it should be done within `openaq-fetch`. I think it should live on its own since I think it'll be helpful to a larger community and shouldn't be hidden inside fetch. At the risk of making everything more complicated, what about a repo with just the script to do the reverse geocoding? We can run it nightly to check for new locations. The resulting output JSON could be saved either back to the GitHub repo (I think my preference since it's still publicly accessible) or could be saved to S3.

**Comment by maxgrossman** [comment]
@jflasher - I plus 1 the openness of github and a separate repo.

The script is updated per the above comments and I also integrated the new locations into the adapter (which will need slight refactoring when we make the new repo). 

Regarding the new repo - aught we implement it now? If so would you want me to do so, or would you want to do the initial setup? 

You are the visionary here, but if I was to envision how it could work, we'd match the sources, master fetch function, adapter structure with the addition of a folder called sources-locations that would hold the station locations for those that need reverse geocoding. Then in the sources JSON of fetch, a 'locations' property would hold the raw github link for adapters that need reverse geocoding. 

This way adding new reverse geocoder scripts is similar to the adapter workflow.

**Comment by jflasher** [comment]
https://github.com/openaq/battuta lives! @maxgrossman you should have an invite to be an admin on it. I think we should put this in place before pulling in the EEA work, no need to just have to change it right away. 

In the spirit of [YAGNI](https://en.wikipedia.org/wiki/You_aren%27t_gonna_need_it), I was thinking we'd be doing this only for EEA, but it sounds like you're thinking of doing it for others? I was thinking of there just being 2 files in the repo. Something like doit.js and locations.json.

doit.js will call out to EEA and get list of all the locations, then compare it to locations.json, see which ones it does not have cities for, reverse geocode them, save back to locations.json and then commit (or alternatively, locations.json could live on S3). 

I'm not against doing something bigger, but I'm not sure we need it? I think we really need it for EEA since there is no concept of city or region at all in the data we get from there.

If you want to run with the script part, I can help make sure it runs on a nightly basis and commits, etc. If we need an EEA token for this, just make sure it gets accessed from environment variable and doesn't get committed.

**Comment by maxgrossman** [comment]
@jflasher here's a snippet regarding incorrect times we can add to the note to eea.

---

We found two inconsistencies between stations records' UTC offsets reported in their `network_timezone` field and their local time zones' UTC offsets.

First, there is a consistent 1-hour difference between local and `network_timezone` reported UTC offsets for the majority of stations (see the table below).

| COUNTRY | NETWORK_TIMEZONE | LOCAL |
| ------ | ------ | ------ |
|Andorra |UTC+01|  UTC+02|
|Germany |UTC+01|  UTC+02|
|Poland |UTC+01|  UTC+02|
|Portugal|UTC|  UTC+01|
|Croatia |UTC+01|  UTC+02|
|Denmark |UTC+01|  UTC+02|
|Finland |UTC+02|  UTC+03|
|Hungary |UTC+01|  UTC +02|
|Macedonia|UTC+01|  UTC+02|
|Italy |UTC+01|  UTC+02|
|Austria|UTC+01|  UTC+02|
|Switzerland|UTC+01|  UTC+02|
|Gibraltar|UTC+01|  UTC+02|
|Ireland |UTC|  UTC+01|
|Great Britain|UTC|  UTC +01|
|Latvia |UTC+02|  UTC+03|
|Malta |UTC+01|  UTC+02|
|Serbia |UTC+01|  UTC+02|
|Sweden |UTC+01|  UTC+02|
|Slovenia |UTC+01| UTC+02|


Is this due to the network time zones not taking into consideration Daylights savings time?

---

Additionally, there are some countries with network_timezones that are either consistent with their local UTC offset, or off two hours from their local offset.

Do you know what is generating this issue?

| COUNTRY | NETWORK_TIMEZONE | LOCAL |
| ------ | ------ | ------ |
|France |UTC-04 (non-continental)|UTC-04 (non-continental)|
|France |UTC (continental)|UTC+02 (continental)|
|Sweden |UTC|UTC+02|
|Czech Republic |UTC|UTC+02|
|Spain |UTC|UTC+02|
|Luxembourg|UTC|UTC+02|
|Slovakia |UTC|UTC+02|
|Belgium |UTC|  UTC+02|

**Comment by olafveerman** [comment]
The first issue seems to be consistent with EEA recommendations on how to deal with the timezone. From http://dd.eionet.europa.eu/vocabulary/aq/timezone/view:

> It is recommended that local standard time (the time without correction for daylight saving time where this is applicable) is used for reporting of observations and aggregated data and derived statistics.

I think we just have to accept this as a limitation of the EEA service.

---

The second seem to be reporting errors that we can flag with the EEA.

---

Either way, I think we should go ahead and keep using `network_timezone` to generate a local timestamp and hope that the EEA can correct this at the source.

cc @jflasher @maxgrossman

**Comment by olafveerman** [comment]
This was implemented and the first adapter deployed to production. (https://github.com/openaq/openaq-fetch/pull/374) 
Closing.
