### ISSUE TITLE
New data - Colombia (Medellín)

### ISSUE THREAD

**Issue by RocketD0g** [openaq/openaq-fetch#318]
**See comment below this one.**

* URL: https://siata.gov.co/siata_nuevo/index.php/mapa
* To see the data: On the map, you should go to Redes -> Siata -> Calidad del aire. 
* I see the following pollutants: 10-PM10 stations, 10-ozone stations, 2 PM2.5 stations, 8 NO2 stations, 1 SO2 (I could be missing some, but that's the rough count)
* Readings are in physical units, which can be found by looking at the time-series associated with the point.

* Coordinates are available by clicking on a given reading and then going to the right-hand panel and clicking "Informacion"
![screen shot 2017-07-07 at 1 43 15 pm](https://user-images.githubusercontent.com/13404290/27969832-7fc61142-631a-11e7-8059-dcd2d73fa80d.png)

* **ISSUE:** The timestamps are unclear, as are some of the measurement average intervals. I've sent an email to the air quality agency, requesting more information.

**Comment by meiamsome** [comment]
It may be better to look at http://www.metropol.gov.co/CalidadAire/Paginas/default.aspx which was easier to reverse engineer (At least for me) and appears to be the same data.

http://modemed.upb.edu.co/micrositio/consultas.php?&especie=GENERAL&proceso=1&tipoDat=0&fecha=2017-05-31

Returns a list of all stations, which you can then use to get individual readings:

http://modemed.upb.edu.co/micrositio/clases_calidadaire.php?idest[]=1&idEsp=2&idEquipo=3&fechaIni=2017-5-01&fechaFin=2017-5-31

Which are then stored in date/value pairs.
I can't decipher all the parameters, maybe it's worth someone who can speak the language having a look

**Comment by RocketD0g** [comment]
Thanks, @meiamsome - this looks great! 

See @meiamsome's comment above - all info appears to be available for PM10, PM2.5 and ozone from this link instead:

http://www.metropol.gov.co/CalidadAire/Paginas/default.aspx

**Comment by yaazkal** [comment]
Hi, when I was about to fill the form to add a new data resource to help #FixtheAQGap I did not considered that site because seems that the information on metropol.gov.co is historical (consolidated month by month) and retrieved from modemed.upb.edu.co as @meiamsome pointed.

The real time information (last 24 hours) comes from siata.gov.co

I can see that `https://siata.gov.co/siata_nuevo/application/assets/js/siata_nuevo/mapa_utils.js` and `https://siata.gov.co/siata_nuevo/application/assets/js/siata_nuevo/mapa_load.js` are scripts that loads and intereact with the data.

See that in the first lines of `mapa_utils.js` they define some urls in vars just to be used in some ajax code later on functions.

If I got some extra time I'm gonna check if I can decipher the url or code to get the air data information as an array or something useful for you. Trying to help because many of the variables and functions are in spanish.

Regards.

**Comment by dolugen** [comment]
@yaazkal Would love to have someone who can bypass the Spanish barrier to look at this.

Does anyone know if the measurement numbers are actually used on the client? All I see are PNG files for the time series graphs. I'm assuming the image files are generated on the server.
