### ISSUE TITLE
Test lodash 4

### ISSUE THREAD

**Issue by olafveerman** [openaq/openaq-fetch#338]
Test what it would entail to upgrade to [Lodash 4](https://github.com/lodash/lodash/wiki/Changelog) and if upgrading to lodash 4 would break anything:

1. [x] run a couple of adapters locally
2. [x] upgrade to lodash 4
3. [x] run the same adapters and compare output

**Comment by jflasher** [comment]
This is going to be closed by https://github.com/openaq/openaq-fetch/pull/350. Working on #343, I just decided to update everything. 

I did catch a (potentially very bad) issue using `_.find` but didn't see anything else going wrong. To test I did a complete fetch with new packages, copied the measurements into a new table, did a complete fetch with old packages and compared the results. Things looked good, though it's a little tricking since they're not exactly the same due to time difference in running the fetch.
