### ISSUE TITLE
Issue with Israel adapter?

### ISSUE THREAD

**Issue by RocketD0g** [openaq/openaq-fetch#450]
Someone just asked about the Israel data, and I noticed the data is 14 days old and doesn't show up as grayed out coordinates. Not sure where the underlying issue is, but flagging here briefly.

**Comment by dolugen** [comment]
I see "Failure to load data url" error for the data source (on fetches endpoint). Though I can access it manually. It is possible that they decided to throttle our connections.

**Comment by jflasher** [comment]
Hmm, if they throttled it, I feel like we should still see some successful requests now and then? I guess they could've blocked completely? I think we ran into something like this before when a url returned a 301 and did a redirect. A browser handles it fine, but the scraper did not. Could you check with something like `curl -v` and see that the url fetch uses isn't returning a 301?

**Comment by RocketD0g** [comment]
As a point of reference, it looks like aqicn.org has the updated data showing on their map. http://aqicn.org/map/#@g/31.8211/35.1672/9z
(I don't know how aqicn.org accesses this specific dataset, but I _presume_ it is in roughly a similar manner to us. That could be an incorrect assumption.)

**Comment by dolugen** [comment]
Preliminary tests show that it's definitely responding with 200 OK. Without any headers set, it responds with "Server busy" (but 200), and with the headers from the adapter, I seem to be getting the correct responses.

```curl -H @header.txt http://www.svivaaqm.net/MenuSite.aspx```

[header.txt](https://github.com/openaq/openaq-fetch/files/1661880/header.txt)

I don't know if the adapter's getting any error, I'll need to check. Otherwise, they could be filtering connections from where the fetch calls are coming from, so they're timing out.

**Comment by jflasher** [comment]
I rotated the instance that fetch runs on so it'll show up with a new IP. If it's being blocked, we should be able to see the data show up again. If that's the case, we should reach out to the source probably and ask what to do since we don't want to be bad citizens.

**Comment by jflasher** [comment]
Just a note that I just looked and Israeli data is updating again so going to close this. We can open again if it becomes an issue.
