### ISSUE TITLE
New data source for Iceland 

### ISSUE THREAD

**Issue by nishadhka** [openaq/openaq-fetch#552]
The data source is https://www.ust.is/einstaklingar/loftgaedi/maelingar/ . There are about 26 stations giving real time data with most of [openaq-data-fromat metadata](https://github.com/openaq/openaq-data-format) details as well.

**Comment by RocketD0g** [comment]
Great, thanks for the heads up on this! I am putting a tag to put this issue on hold.

**Comment by RocketD0g** [comment]
Great - thanks so much for the heads up on this!

**Comment by RocketD0g** [comment]
Hi @Stalfur  - any update on this? We'd love to add Icelandic data.

**Comment by Stalfur** [comment]
Hi @RocketD0g - yes we are now rolling out an API, I'll keep this updated, should be up within a month.

**Comment by Stalfur** [comment]
https://api.ust.is/aq is now live - we start with station info and hourly values for past 24 hours.

**Comment by Stalfur** [comment]
If there is anything that would be better for OpenAQ then we can accommodate that probably

**Comment by RocketD0g** [comment]
Wow, awesome @Stalfur! This is great! **Thanks for sharing this!** It looks like all the metadata we need on our end is in there, but @sruti will be the one to make sure I'm not speaking too quickly.

Two small clarifications: 

(1) I'm assuming since the data are shared hourly that these are hourly-averaged data? (We've had a couple instances where data are shared hourly but the time-average on a given measurement itself is shorter, so just double checking).

(2) I also assume the time is reported in GMT, UTC+0, the timezone for Iceland as I understand it, but also just double-checking.

Lastly, @Stalfur - would you be open for us potentially chatting with you via email about the creation of this API? We would love to amplify this great example of sharing key air quality data in a programmatic and open way! If so, please shoot me an email at christa@openaq.org (or feel free to leave yours here and I will reach out to you, but I realize that your email would then be shared publicly).

Thanks again - this is fantastic!

**Comment by Stalfur** [comment]
Hello @RocketD0g 

(1) Yes these are hourly averaged data. We will add to the clarification, adding units and averaged time.

(2) Yes luckily being at UTC+0 allows us to pay no mind to timezone conversions for now.

Lastly yes I'd be happy to, I'll drop you an e-mail from my work email.

**Comment by olafveerman** [comment]
A first version for the adapter is implemented in the Pull Request above.

Thanks @Stalfur for providing the data through this API, it was a breeze to get it in.

There are a couple of minor outstanding issues that we need to address. I hope you can help with a couple of them:

* what units are the parameters reported in? Do they follow the [units preferred by OpenAQ](https://github.com/openaq/openaq-data-format#preferred-units)?
* would you like to add a contact email for UST in the metadata of the source? If not, we'd use info@openaq.org as a fall-back

**Comment by sruti** [comment]
This source has been added in #659!
