### ISSUE TITLE
Australia high SO2 (potential bug?) 

### ISSUE THREAD

**Issue by ReaRuiRay** [openaq/openaq-fetch#646]
OpenAQ reports very high SO2 near Sydney (~300ppb) while the governmental website shows very low concentrations. Not sure whether there is something wrong or not. 

<img width="1468" alt="Screen Shot 2019-12-11 at 11 20 35 AM" src="https://user-images.githubusercontent.com/11169226/70639542-9f879380-1c08-11ea-8f3a-99c38b7e2ab2.png">
<img width="892" alt="Screen Shot 2019-12-11 at 11 20 17 AM" src="https://user-images.githubusercontent.com/11169226/70639543-9f879380-1c08-11ea-90d9-46bcc150b5e3.png">

**Comment by andrewharvey** [comment]
Thanks for catching this bug! The adaptor was incorrectly counting columns for rows which didn't have a region, for example "Randwick" was broken but "Cook And Philip" was okay. This resulted in the paramaters and values being off by one so it was using the PM10 value for SO2 :open_mouth: ! In the last week we've had hazardous levels of particles due to bushfire smoke.

The linked PR should fix this going forward, but I have no idea how to go about fixing the incorrect historical data. The good news is NSW provide a data download service (see #647) so we should be able to just replace historical data from there rather than the tedious task of untangling the data which has been logged.

Happy to help with these, but I'm going to need some guidance :pray:

**Comment by ReaRuiRay** [comment]
Thanks @andrewharvey for addressing this! You are most helpful!
As for the historical data, I think the platform's mission at this stage is more focused on realtime feeding as it affects more people. As a researcher myself, it would be great to have global historical air quality data but it takes lots of efforts (it's worth the efforts!). We have some related discussions at https://github.com/openaq/openaq-upload/issues/21
