### ISSUE TITLE
Mexican AQ data

### ISSUE THREAD

**Issue by sruti** [openaq/openaq-fetch#672]
Hourly data can be found here: https://sinaica.inecc.gob.mx/ by clicking on 'Modulos' then 'Datos crudos' and then choosing the station. Requires scraping but looks straightforward.
 
To verify/investigate:
- [ ] hourly-averaged
- [ ] station coordinates
- [ ] easier, programmatic way to access the data
- [ ] doesn't duplicate existing Mexican data from AirNow

**Comment by RocketD0g** [comment]
For programmatic data availability: 

Noticing there is an API available for CO (only?) data: 
https://api.datos.gob.mx/v2/sinaica 

Found here: https://datos.gob.mx/ under "Calidad del Aire de SINAICA "

**Comment by magsyg** [comment]
The source https://api.datos.gob.mx/v2/sinaica, looks like it has been inactive since 2018, found a similiar type of source: https://api.datos.gob.mx/v2/calidadAire, but it is also inactive from 2019. 
I could not find any place where they Mexico has stored their air quality data. 

The only place I found a possibility of fetching correctly is by going through each stations, from pages like this https://sinaica.inecc.gob.mx/estacion.php?estId=39, where all data seems to be perfect for us.
These pages have rawdata, correct timestamps, hourly data (But the stations seems to be inactive some hours of the day), coordinates (But they are given in degrees and not decimals).
It looks like these pages needs to be scraped, and run through each of the station pages. The estID of the stations seem to not be sorted numerical and there are a lot of blank ID sand empty station pages, so we may need to run through a lot of pages to fetch all the data. I am not sure if this is the desired approach

**Comment by magsyg** [comment]
Found this source, it looks like it is not included in the source above or AirNow
 Source: http://www.nl.gob.mx/servicios/mapa-de-la-calidad-del-aire
The data is raw, and is updated hourly/daily. Is stationlevel and coordinates are given in the map. It can also be downloaded to csv from this page:
http://aire.nl.gob.mx:81/Sima2017reportes/ReporteSemanalSimaIMaximos.php

Looks to only affect the city of Monterrey

**Comment by magsyg** [comment]
Also found this for the city of Guadalajara in Mexico http://siga.jalisco.gob.mx/aire2020/mapaf2019, most of the metadata is given here in a pdf: http://siga.jalisco.gob.mx/aire2017/Info/NumeraliaImeca.pdf, and it looks like the data is raw and hourly from the datasets given here: http://siga.jalisco.gob.mx/aire2020/concentracionesh2020, does not look like this data is available in our database yet
