### ISSUE TITLE
Several countries in EEA we are not pulling

### ISSUE THREAD

**Issue by RocketD0g** [openaq/openaq-fetch#677]
Some **real** low-hanging fruit: Looks like there are several countries we are not pulling from, from EEA [(via direct download option)](http://discomap.eea.europa.eu/map/fme/AirQualityUTDExport.htm):

- Bosnia - BA
- Bulgaria* - BG 
- Cyprus - CY
- Denmark* - DK
- Estonia - EE
- Georgia - GE
- Greece - GR
- Romania - RO
- Sweden - (Which we have previously ingested, but is a broken adapter currently)

*It currently _looks_ like we have Bulgarian data and Denmark data, but this is due to an issue with the AirNow data source mislabelling a two-letter country code.

**Comment by sruti** [comment]
Not sure if this is a recent development (because I think we looked before and it wasn't available), but Italy data is available through the EEA source as well.

**Comment by sruti** [comment]
With #694 and #707, we now have Bulgaria, Cyprus, Estonia, Greece, Romania, and Georgia*!
Still remaining to add:
- Bosnia
- Italy 
- Sweden

Denmark - When looking at the map, it looks like we don't have Denmark data because they don't report PM2.5, PM10 data but we do have O3, NO2, CO, SO2
*We have the source file in place to get Georgia data but we currently aren't pulling in any because its stations don't exist in the [list of EEA stations](http://battuta.s3.amazonaws.com/eea-stations-all.json). Will investigate and open a separate issue.
