### ISSUE TITLE
ARPA Lazio adapter uses incorrect timezone

### ISSUE THREAD

**Issue by alexdunncs** [openaq/openaq-fetch#708]
'Europe/Rome' observes DST, but source data is consistently recorded at UTC+01:00 (per data provider).

Should use 'Etc/GMT-1' timezone instead.

**Comment by sruti** [comment]
That's a good catch! Because that's what the source is reporting and it's OpenAQ's policy to report the data 'as-is', we don't want to modify the adapter with the change. Otherwise it's a lot of work to maintain updates to the adapter (what if they fix it in a couple months?) and it becomes a slippery slope. If you have a contact at ARPA though, it would be good to let them know!

**Comment by AJExtravaganza** [comment]
Hi @sruti!  Caught your email and will probably reach out in the slack next week :)

Sorry, I may have been unclear where the error lies - per the data provider, their measurements are (as a matter of policy) recorded in Central European Time (UTC+1).  This is not an oversight (ie it will not change, as it is not an error but an intentional design choice to use standard time).

Using the 'Europe/Rome' tz seems more like an erroneous assumption on our part than a matter of standardisation in this case, no?

**Comment by majesticio** [comment]
I have reviewed the timezone and it appears to be correct for this region of Italy.
