### ISSUE TITLE
Backcalculating AQI to concentration

### ISSUE THREAD

**Issue by olafveerman** [openaq/openaq-fetch#79]
For Iran (#51) and possibly other sources, we may have to back-calculate AQI values to pollutant concentration. It seems that Iran uses the EPA's methodology. Should we write a generic tool in lib that does this calculation?
## Data

This tool would accept an object, or array of objects with a measurement. Each measurement needs at least the parameter and the value. We can store a reference to the original value and an annotation about the conversion.

``` js
{ 
  city: 'Tehran',
  location: 'emam khomeyni',
  parameter: 'so',
  value: 150
}
```

would become something like:

``` js
{ 
  city: 'Tehran',
  location: 'emam khomeyni',
  parameter: 'so',
  unit: 'ppm',
  value: 0.22,
  original: {
    value: 150,
    methodology: 'EPA AQI to concentration'
  }
}
```
## Methodology

On page 16 of this [EPA publication](http://www3.epa.gov/ttn/oarpg/t1/memoranda/rg701.pdf):

![image](https://cloud.githubusercontent.com/assets/751330/13251536/eef1a76c-d9fe-11e5-9cef-98a1c9ed6107.png)

@RocketD0g Can we use this?

cc @jflasher

**Comment by RocketD0g** [comment]
I think we'll eventually need to back-calculate to get some data sources, but here's an issue specific to non-US places using the US EPA method and us attempting to back calculate:

-In the calc above referenced by @olafveerman, Ip is essentially a _f_(Cp), so the main issue (in addition to confirming they are using that method) will be to determine how a given place has decided on the time-average they use for Cp. 

US EPA says, "The AQI reported for ground-level ozone and fine particles (PM2.5) is based on an average of hourly data. For ozone, the AQI is based on the maximum observed 8-hour average from midnight to midnight. For PM2.5, the AQI is simply the 24-hour average. For AQI values reported in real-time, before a full day's data are available, the AQI is based on a surrogate calculation*. " 
_Source:  https://docs.airnowapi.org/aq101_

My sense is many places will plug in the Cp for whatever time resolution they measured, not necessarily following the straight US method. But it's so hard to say if they don't explicitly say on their website. I guess I'd hold off on building this back calculating tool until we have a concrete place to apply it. 

Looking back at the Iran data** in #51 , playing around with their site some more, I get different daily average values when looking at the map of reporting stations one way versus another, the 'daiy' archive and the AQI archive daily value listed for a station. Therefore, I'm not even sure what we would use as the daily AQI for a given pollutant, let alone assuming they are using the formula above to back calculate an AQI out of it. 

For back calculating, if we were to build a tool, I'd say we should go for the Chinese AQI back calculation, as most of the websites reporting AQ in China report only the AQI (that I have seen), and we will know we are back-calculating correctly since we will be using the Chinese AQI algorithm on Chinese data. I will need to track down their AQI but I believe it is publicly available somewhere and will make an issue/assign myself to it.


*This is the surrogate calculation referenced by EPA: (http://www3.epa.gov/airnow/ani/pm25_aqi_reporting_nowcast_overview.pdf), which takes essentially a 3-12 hour average of PM2.5 data, depending on how much the data is fluctuating. Given the weighting system and that missing data for a given hour would be hard to spot, I think it is mathematically impossible to back calculate to physical concentrations for a given hour, even if you know the last 12 hours of reported NowCast AQI. I thought it'd be possible, but I couldn't get it ever to mathematically pan out - maybe I made a mistake with playing around with the equation here for the NowCast system (http://www3.epa.gov/airnow/ani/pm25_aqi_reporting_nowcast_overview.pdf). At any rate, on the bright side, my sense is that most places don't adopt the NowCast formula for their real-time data so that you can likely back calculate using an hourly interval.

**I actually do think that the 'data archive' (http://31.24.238.89/home/DataArchive.aspx) is likely physical concentrations given the titles of the other sections and playing around with the numbers over multiple days. But there's no time stamp and no way to verify this (trying to re-calculate the reported AQI on other parts of the site from these numbers pans out close, but not precisely).

**Comment by jflasher** [comment]
Based on response from @RocketD0g in #89, going to close this as well.
